version: 0.1

env:
  variables:
    REACT_APP_API_URL:  https://geniepad.brocoders.xyz

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR;
      - npm install -g typescript
      - npm install aws-sdk --save
      - npm i
      - cd $CODEBUILD_SRC_DIR/s3-deployment-custom-resource; npm install
      - cd ../
  pre_build:
    commands:
    #- cd $CODEBUILD_SRC_DIR; node configure.js $STAGE
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/build; zip -r ../package.zip *
      - aws cloudformation package --template-file app-sam.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
artifacts:
  files:
    - app-output_sam.yaml
    - package.zip
  discard-paths: yes
